//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITI.Smart.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public int id { get; set; }
        public string name { get; set; }
        public int fk_country { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
